#!/usr/bin/env bash

# Execute :PlugInstall automatically. Suppress
# the vim exit code, which always returns 1.
if [[ -d ~/.vim/plugged ]]; then
  echo "Updating vim plugins..."
  vim -es -u ~/.vim/vimrc -i NONE -c "PlugUpdate" -c "qa" || true
else
  echo "Installing vim plugins..."
  vim -es -u ~/.vim/vimrc -i NONE -c "PlugInstall" -c "qa" || true
fi
