#!/usr/bin/env bash

url=https://github.com/neovim/neovim-releases/releases/download/v0.10.3/nvim-linux64.tar.gz
prefix=~/.local

# Early exit when nvim is already installed.
if [[ -x $prefix/bin/nvim ]]; then
  exit 0
fi

# Fetch and unpack neovim.
curl -fsSL $url | tar -xz --strip-components=1 -C $prefix
