#!/usr/bin/env bash

# Update tmux-sensible.
if [[ -d ~/.local/share/tmux-sensible ]]; then
  echo "Updating the tmux-sensible directory..."
  git -C ~/.local/share/tmux-sensible pull
else
  echo "Cloning the tmux-sensible repository..."
  git clone https://github.com/tmux-plugins/tmux-sensible ~/.local/share/tmux-sensible
fi
